---
title: "PROJECT PROPOSAL"
subtitle: ""
author: Nicholas Mallis
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article

bibliography: ../references.bib
csl: ../apa.csl
---


#Introduction to Research Project

For the analysis project, I propose to examine the relationship between education level and COVID-19 vaccination rate by county for all counties in the Unites States. Kaiser Health News and other sources have reported this relationship on the individual level using data from surveys and qualitative research.  KHN released a report on June 11 that outlines the profile of the unvaccinated. They state that “compared to those who have received a covid-19 vaccine, unvaccinated adults are younger, less educated, more likely to be republicans, people of color, and uninsured.” You can see the whole report here. https://www.kff.org/coronavirus-covid-19/poll-finding/kff-covid-19-vaccine-monitor-profile-of-the-unvaccinated/ Although this has been examined using surveys from individual participants, there are no current reports or published papers that have studied this relationship using aggregate data from all counties in the US. The proposed analysis could provide more information on this association on a larger scale.

In order to explore this relationship between education level and vaccination rates at the county level, I will pull in data from several different sources and merge them together. Most county level data are tagged with a Federal Information Processing Standards (FIPS) number. This will be the ID variable for merging these datasets. 

#Main Outcome
My main outcome will be percent of eligible people (age 12+) in a county that have been fully vaccinated. I will obtain this from the CDC’s open-source dataset, "COVID-19 Vaccinations in the United States, County." Here is the link to this dataset -> https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh This dataset “represents all vaccine partners including jurisdictional partner clinics, retail pharmacies, long-term care facilities, dialysis centers, Federal Emergency Management Agency and Health Resources and Services Administration partner sites, and federal entity facilities.” It is updated regularly and rapidly changing so I will need to decide on a cut-off date for my analysis at some point.

#Main Exposure:
The main exposure will be percent of adults in each county who have a bachelor’s degree or higher. The most current county level data on education is available on the USDA’s Economic Research website and can be found if you click here -> https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/ This dataset includes information on education level for all years, but I will subset the data to only include observations from the most current year. The most current calculations of education level by county are 5- year averages based on 2015-2019 and they come from the Census Bureau’s American Community Survey. 

#Possible Confounders:
There are other possible confounders that I am interested in examining including poverty, unemployment, median household income, locality (urban or rural) and health insurance rate. In order to obtain this information, I will pull in data from a few more sources. The first three variables that I list are all available through the USDA Economic Research Service as well, but in different datasets.  They can be found here on the USDA website -> https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/ The county poverty estimates are model-based estimates from the U.S. Census Bureau's Small Area Income and Poverty Estimate (SAIPE) program. The county unemployment rates are from the Bureau of Labor Statistics (BLS) Local Area Unemployment Statistics (LAUS) program. The county median household income variable comes from the U.S. Census Bureau's Small Area Income and Poverty Estimate (SAIPE) program. The locality (urban or rural) variable comes from from the Rural-Urban Continuum Codes Dataset which is also managed by USDA. This can be found here -> https://www.ers.usda.gov/data-products/rural-urban-continuum-codes/

Unfortunately, I am having trouble finding data on health insurance rate by county in the US, but I think it would be useful so I will keep looking. 

There will be close to 3,000 observations in the dataset (one observation for each county).

#Brief Analysis Plan: 
After merging, cleaning, and wrangling the data, I will produce summary statistics for each variable. I will plot the main exposure (percent of adults in each county who have a bachelor’s degree or higher) and the main outcome (percent of eligible people (age 12+) in a county that have been fully vaccinated) on a scatterplot to examine the possible linear relationship.  I will use linear regression modeling to calculate the beta estimate for the bivariate relationship between education level and county COVID-19 vaccine rate. I will test each potential confounder to see if they are qualified to be included in the model based on confounding criteria. Eventually, I will have a multivariate model that provides a beta estimate for the relationship between education level and COVID-19 vaccine rate while controlling for confounders. 

I am also considering generating some plots that use maps. I have not done this in R before so it could be a good learning experience.

#Note on the Analysis Plan: 
Due to possible statistical issues, I am a little worried about using a percentage as my outcome. I am considering using some sort of transformation on the outcome (maybe arcsin) or possibly categorizing the outcome into two levels (1=High Vaccination Rate, 0=Low Vaccination Rate). I realize that we lose a lot of information in categorizing, but it could be the way to go. A third idea could be to model the vaccine count as the outcome and control for population of each county, but I'm not sure that would be as interpretable because I'm really most interested in percentages. Let me know if you have any suggestions on this or if you think modeling a percent is okay.

#Last Note: 
I realize that there is a whole set of issues that can occur with an ecological study. I also realize that you asked us to find "a dataset" and I have found several to merge instead of one just one. If you think this is not a good way to do the project, I am happy to pivot and find something different. Like most people right now, I have vaccination rates on the mind and really wanted to do something with that as the outcome. This was the best way I could come up with. Originally, I wanted to do an analysis that had county “voting majority Trump” as the predictor, but with a quick internet search, I realized that has been run into the ground already. 





